name: eval_online
services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - production_net


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - production_net


  #jupyter:
   # image: quay.io/jupyter/pytorch-notebook:pytorch-2.5.1
    #container_name: jupyter
    #ports:
     # - "8888:8888"
   # environment:
     # - FOOD11_DATA_DIR=/mnt/Food-11
    #volumes:
     # - ./workspace:/home/jovyan/work
      #- food11:/mnt
    #command: >
     # bash -c "python3 -m pip install alibi-detect && start-notebook.sh"

volumes:
  grafana_data:



networks:
  production_net:
    external: true
